server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-auth:5432/authdb
    username: auth
    password: secret
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: verySecretKeyChangeMe

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka