server:
  port: 8082

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-user}:${DB_PORT:5432}/${DB_NAME:userdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:secret}

  jpa:
    hibernate:
      ddl-auto: update

service:
  auth: http://auth-service:8081

jwt:
  secret: 5bf8505e7f1171cbf12fd4904860cf2ad99b3f3bc98fc2de63f9469dc1fa7aac

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:discovery-service}:8761/eureka
